defaults:
  - backbone: masked_vggt

name: spfsplatv2-l

opacity_mapping:
  initial: 0.0
  final: 0.0
  warm_up: 1


num_surfaces: 1
predict_opacity: false

gaussians_per_pixel: 1

gaussian_adapter:
  gaussian_scale_min: 0.5
  gaussian_scale_max: 15.0
  sh_degree: 4



visualizer:
  num_samples: 8
  min_resolution: 256
  export_ply: false

apply_bounds_shim: true

gs_params_head_type: dpt_gs
pose_free: true
pretrained_weights: ""
pose_make_baseline_1: false
pose_make_relative: true


estimating_focal: false
estimating_pose: true